# fly.toml app configuration file generated for datingappmrdancer on 2023-08-10T19:48:56+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datingappmrdancer"
primary_region = "waw"

[build]
  image = "mrdancer/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dphyox40m"
  CloudinarySettings__ApiKey="158328774786811"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
